Repository State-of-Rhode-Island-eCMS/ecms_profile, pull requests merged in 2020-12, with the labels that each got.

#134 Fix to allow drush to run migration tools migrations
  CHANGELOG.md
  composer.json
Labels: approved, configuration, drupal

#136 Prepare changelog for 0.2.6 release
  CHANGELOG.md
Labels: release

#138 Permissions refinement
  CHANGELOG.md
  ecms_base/config/install/user.role.content_author.yml
  ecms_base/config/install/user.role.content_publisher.yml
  ecms_base/config/install/user.role.form_author.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.profile
  ecms_base/modules/custom/ecms_blocks/ecms_blocks.module
Labels: configuration, drupal

#139 Promo reference block type, content components bg color, missing form settings
  CHANGELOG.md
  ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.content_components.default.yml
  ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.page_title_with_photo.default.yml
  ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.text_card_collection.default.yml
  ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.block_content.content_components.default.yml
  ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.content_components.field_components_bg_color.yml
  ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_components_bg_color.yml
  ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml
  ecms_base/features/custom/ecms_promotions/config/install/block_content.type.promotion_reference.yml
  ecms_base/features/custom/ecms_promotions/config/install/core.entity_form_display.block_content.promotion_reference.default.yml
  ecms_base/features/custom/ecms_promotions/config/install/core.entity_view_display.block_content.promotion_reference.default.yml
  ecms_base/features/custom/ecms_promotions/config/install/field.field.block_content.promotion_reference.field_promotions.yml
  ecms_base/features/custom/ecms_promotions/config/install/field.storage.block_content.field_promotions.yml
  ecms_base/features/custom/ecms_promotions/config/install/language.content_settings.block_content.promotion_reference.yml
  ecms_base/features/custom/ecms_promotions/config/install/language.content_settings.paragraph.promotion_reference.yml
  ecms_base/features/custom/ecms_promotions/ecms_promotions.info.yml
  ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--content-components.html.twig
  ecms_base/themes/custom/ecms/templates/fields/field--block-content--field-promotions.html.twig
Labels: bug, configuration, drupal, twig

#140 Prepare changelog for 0.2.7 release
  CHANGELOG.md
Labels: release

#133 Publication node migrations
  CHANGELOG.md
  ecms_base/features/custom/ecms_publications/config/install/views.view.publications.yml
  ecms_base/features/custom/ecms_publications/ecms_publications.info.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/README.md
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_subtypes.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_types.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration_group.ecms_covid_publications.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/ecms_covid_publication_migrate.info.yml
  ecms_base/modules/custom/ecms_migration/README.md
  ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.migrations.yml
  ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.settings.yml
  ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_publications.yml
  ecms_base/modules/custom/ecms_migration/config/schema/ecms_migration.schema.yml
  scripts/develop.sh
Labels: configuration, drupal

#141 Updated publisher and site admin role default permissions
  CHANGELOG.md
  ecms_base/config/install/user.role.content_publisher.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.profile
Labels: configuration, drupal

#142 Prepare changelog for 0.2.8
  CHANGELOG.md
Labels: release

#143 Site admin role permissions
  CHANGELOG.md
  composer.json
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.profile
Labels: configuration, drupal

#145 Add cache tags to global block
  CHANGELOG.md
  ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/PromotionsGlobalBlock.php
Labels: drupal, php

#144 Fixed the rss import to ignore the sub-category
  CHANGELOG.md
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_subtypes.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml
Labels: configuration, drupal

#147 Publications list theming and preprocessing
  CHANGELOG.md
  ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publications_list.created.yml
  ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publications_list.status.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.paragraph.publication_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.paragraph.publications_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.node.publication.default.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.node.publication.teaser.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.paragraph.publication_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.paragraph.publications_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_audience.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_title.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publications_list.field_publication_language.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publications_list.field_publication_types.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publications_list.field_publications_manual.yml
  ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_language.yml
  ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_list_audience.yml
  ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_types.yml
  ecms_base/features/custom/ecms_publications/config/install/language.content_settings.paragraph.publications_list.yml
  ecms_base/features/custom/ecms_publications/config/install/paragraphs.paragraphs_type.publication_list.yml
  ecms_base/themes/custom/ecms/ecms.theme
  ecms_base/themes/custom/ecms/templates/content/node--publication--teaser.html.twig
  ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--publication-list.html.twig
Labels: configuration, drupal, php, twig, yml

#148 Prepare changelog for 0.2.9
  CHANGELOG.md
Labels: release

#149 Workflow updates - moderation dashboard and transition states
  CHANGELOG.md
  ecms_base/config/install/page_manager.page.moderation_dashboard.yml
  ecms_base/config/install/page_manager.page_variant.moderation_dashboard-panels_variant-0.yml
  ecms_base/config/install/views.view.moderation_dashboard_recent_changes.yml
  ecms_base/ecms_base.profile
  ecms_base/modules/custom/ecms_workflow/config/install/workflows.workflow.editorial.yml
Labels: documentation, drupal, yml

#150 Add an admin sub-theme of Claro for eCMS customizations
  .gitignore
  CHANGELOG.md
  ecms_base/config/install/system.theme.yml
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.profile
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_breadcrumbs.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_content.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_help.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_local_actions.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_messages.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_page_title.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_primary_local_tasks.yml
  ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_secondary_local_tasks.yml
  ecms_base/themes/custom/ecms_claro/css/style.css
  ecms_base/themes/custom/ecms_claro/ecms_claro.info.yml
  ecms_base/themes/custom/ecms_claro/ecms_claro.libraries.yml
Labels: approved, configuration, drupal, php

#151 Add audience tags to the Covid publication import
  CHANGELOG.md
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_types.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml
  ecms_base/modules/custom/ecms_covid_publication_migrate/ecms_covid_publication_migrate.install
Labels: configuration, drupal, php

#153 Add the missing contextual links for Layout Builder blocks
  CHANGELOG.md
  composer.json
Labels: configuration, drupal

#154 Add menu links to create new syndicated sites in a hub.
  CHANGELOG.md
  ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.links.action.yml
  ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.links.menu.yml
Labels: configuration, drupal

#155 Move update hooks
  CHANGELOG.md
  ecms_base/ecms_base.install
  ecms_base/ecms_base.profile
Labels: configuration, drupal, php

#156 Update user permissions to include new paragraph and menus
  CHANGELOG.md
  ecms_base/config/install/user.role.anonymous.yml
  ecms_base/config/install/user.role.authenticated.yml
  ecms_base/config/install/user.role.content_author.yml
  ecms_base/config/install/user.role.content_publisher.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.install
Labels: approved, configuration, drupal

#157 Add card paragraph bundle
  CHANGELOG.md
  ecms_base/config/install/user.role.anonymous.yml
  ecms_base/config/install/user.role.authenticated.yml
  ecms_base/config/install/user.role.content_author.yml
  ecms_base/config/install/user.role.content_publisher.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.card.default.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.card.default.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.card.field_background_color.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.card.field_card_title.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.card.field_components.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_background_color.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.card.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.text_card.yml
  ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--content-components.html.twig
  ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--card.html.twig
Labels: configuration, drupal, twig, yml

#158 Purge modules
  CHANGELOG.md
  composer.json
  ecms_acquia/config/install/purge.logger_channels.yml
  ecms_acquia/config/install/purge.plugins.yml
  ecms_acquia/config/install/purge_queuer_coretags.settings.yml
  ecms_acquia/ecms_acquia.info.yml
  ecms_base/ecms_base.install
Labels: configuration, drupal, json, php, yml

#159 Prepare changelog for the 0.3.0 release
  CHANGELOG.md
Labels: release

#160 Fix embed paragraph display modes
  CHANGELOG.md
  ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.default.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.preview.yml
Labels: configuration, drupal, yml

#161 Prepare changelog for 0.3.1
  CHANGELOG.md
Labels: approved, release

#162 Add the missing theme schema to allow translation
  CHANGELOG.md
  ecms_base/ecms_base.install
  ecms_base/themes/custom/ecms/config/install/ecms.settings.yml
  ecms_base/themes/custom/ecms/config/schema/ecms.schema.yml
  ecms_base/themes/custom/ecms/ecms.theme
  ecms_base/themes/custom/ecms/theme-settings.php
Labels: approved, configuration, php, security

#165 Updated language sorting
  CHANGELOG.md
  ecms_base/themes/custom/ecms/ecms.theme
Labels: approved, drupal, php

#166 Add interface translation permission
  CHANGELOG.md
  ecms_base/config/install/user.role.content_author.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.install
Labels: configuration, drupal, php

#167 Prepare changelog for 0.3.3
  CHANGELOG.md
Labels: release

#168 Fixed url value of search result teasers
  CHANGELOG.md
  ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig
Labels: twig

#169 Memcache added and misc performance updates
  .github/workflows/develop.yml
  composer.json
  ecms_base/config/install/system.performance.yml
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.install
  scripts/develop.sh
Labels: approved, configuration, drupal, json, php, yml

#171 Resolve commas breaking search teaser paths
  CHANGELOG.md
  ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig
Labels: twig

#172 Add language filter to publication list
  CHANGELOG.md
  ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.paragraph.publication_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.paragraph.publication_list.default.yml
  ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_language.yml
  ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_list_language.yml
  ecms_base/themes/custom/ecms/ecms.theme
  ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--publication-list.html.twig
Labels: configuration, drupal, php, twig, yml

#173 Memcache updates
  .github/workflows/develop.yml
  CHANGELOG.md
  ecms_base/ecms_base.info.yml
  ecms_base/ecms_base.install
Labels: approved, configuration, drupal, php, yml

#175 Fix syntax error in number_format
  CHANGELOG.md
  ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig
Labels: bug

#177 Refactor the ecms_api_publisher module to handle entity references
  CHANGELOG.md
  ecms_base/modules/custom/ecms_api_notification_publisher/src/NotificationPublisher.php
  ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php
  ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiSyndicate.php
  ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
  ecms_base/modules/custom/ecms_api_publisher/src/Plugin/QueueWorker/EcmsApiSyndicateQueueWorker.php
  ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiPublisherTest.php
  ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiSyndicateTest.php
  ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php
  ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Plugin/QueueWorker/EcmsApiSyndicateQueueWorkerTest.php
  phpunit.xml
Labels: drupal, php

#180 Allow publication nodes to be syndicated to other sites.
  CHANGELOG.md
  ecms_base/modules/custom/ecms_api/src/EcmsApiBase.php
  ecms_base/modules/custom/ecms_api_publication_publisher/README.md
  ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.info.yml
  ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.module
  ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.services.yml
  ecms_base/modules/custom/ecms_api_publication_publisher/src/PublicationPublisher.php
  ecms_base/modules/custom/ecms_api_publication_publisher/tests/src/Unit/PublicationPublisherTest.php
  ecms_base/modules/custom/ecms_api_publisher/README.md
  ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
  ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php
Labels: documentation, drupal, php

#182 Added the missing cache context for publications
  CHANGELOG.md
  ecms_base/themes/custom/ecms/ecms.theme
Labels: drupal, php

#183 Prepare changelog for the 0.3.8 tag.
  CHANGELOG.md
Labels: release

#184 Lock PHP version for CI workflows
  .github/workflows/develop.yml
  CHANGELOG.md
Labels: approved, configuration, yml

#185 Add logic to use node's langcode for displaying notifications
  CHANGELOG.md
  ecms_base/ecms_base.install
  ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SiteNotificationsBlock.php
  ecms_base/themes/custom/ecms/config/optional/block.block.sitenotifications.yml
  ecms_base/themes/custom/ecms/templates/blocks/block--sitenotifications.html.twig
Labels: configuration, drupal, php, twig, yml

#186 Fixed the missing permissions for the content author
  .github/workflows/develop.yml
  CHANGELOG.md
  ecms_base/config/install/user.role.content_author.yml
  ecms_base/config/install/user.role.form_author.yml
  ecms_base/config/install/user.role.site_admin.yml
  ecms_base/ecms_base.install
  ecms_base/themes/custom/ecms/ecms.theme
Labels: configuration, drupal

#187 Prepare changelog for 0.3.9 release
  CHANGELOG.md
Labels: release

#188 Added an h3 to the title search and a default value for the title
  CHANGELOG.md
  ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page.yml
Labels: configuration, drupal

#189 Allow the 'Card' paragraph to be translatable
  CHANGELOG.md
  ecms_base/features/custom/ecms_paragraphs/config/install/core.base_field_override.paragraph.card.created.yml
  ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.paragraph.card.yml
Labels: approved, configuration, drupal
